install:
  - sudo apt-get install linux-image-generic-lts-trusty
  - sudo reboot
  - sudo apt-get update && sudo apt-get install wget
  - wget -qO- https://get.docker.com/ | sh
  - pwd && ls -la

script:
  - ./run
